#include <common.h>
#include "CTRRandomizer_database.h"
#include "reward_enums.h"
#include "messages_handler.h"

#ifndef FALSE
#define FALSE  0
#endif

#ifndef TRUE
#define TRUE  1
#endif

#define DB_END -1
#define DB_RAMMARKER_START 0xDADB, 0x0D00, 0xDADB
#define DB_RAMMARKER_END 0xDADB, 0x0DAA, 0xDADB

static unsigned short rando_database[];

/* Potentially removable, since it mirrors the GemColor enum */
enum CupIds {
    CUP_RED = 100,
    CUP_GREEN,
    CUP_BLUE,
    CUP_YELLOW,
    CUP_PURPLE
};

/*
Fetch a value from the randomizer database using the given key.
If the value cannot be found, return the key as value and set the
fetch result to not_found.
This function is sped up using dynamic jump offsets, making subsequent queries
faster. However, this requires the settings to be grouped by types, instead
of being randomly arranged.
*/
int database_fetch(
    int db_key,
    int *fetch_result
)
{
    int i = 0;

    for (; rando_database[i] != DB_END; i += 3)
    {
        // If we have found our value, set output
        if ((rando_database[i] << 16) | rando_database[i + 1] == db_key)
        {
            *fetch_result = DB_VALUE_OK;
            return (int) (rando_database[i + 2]);
        }
    }

    // If we get here, then we didn't find what we were looking for
    *fetch_result = DB_VALUE_NOTFOUND;
    char dbkey_as_text[8 + 1];
    sprintf(dbkey_as_text, "%x", db_key);
    enqueue_message(
        MSGTYPE_DBFETCH_ERROR,
        dbkey_as_text
    );
    return db_key;
}

static unsigned short rando_database[] = {
    DB_RAMMARKER_START,
    /* LEVEL IDS FOR RANDOM WARP PADS */
    DB_PREFIX_LEVELIDS | CRASH_COVE,     0, CRASH_COVE,
    DB_PREFIX_LEVELIDS | ROO_TUBES,      0, ROO_TUBES,
    DB_PREFIX_LEVELIDS | TIGER_TEMPLE,   0, TIGER_TEMPLE,
    DB_PREFIX_LEVELIDS | COCO_PARK,      0, COCO_PARK,
    DB_PREFIX_LEVELIDS | MYSTERY_CAVES,  0, MYSTERY_CAVES,
    DB_PREFIX_LEVELIDS | BLIZZARD_BLUFF, 0, BLIZZARD_BLUFF,
    DB_PREFIX_LEVELIDS | SEWER_SPEEDWAY, 0, SEWER_SPEEDWAY,
    DB_PREFIX_LEVELIDS | DINGO_CANYON,   0, DINGO_CANYON,
    DB_PREFIX_LEVELIDS | PAPU_PYRAMID,   0, PAPU_PYRAMID,
    DB_PREFIX_LEVELIDS | DRAGON_MINES,   0, DRAGON_MINES,
    DB_PREFIX_LEVELIDS | POLAR_PASS,     0, POLAR_PASS,
    DB_PREFIX_LEVELIDS | CORTEX_CASTLE,  0, CORTEX_CASTLE,
    DB_PREFIX_LEVELIDS | TINY_ARENA,     0, TINY_ARENA,
    DB_PREFIX_LEVELIDS | HOT_AIR_SKYWAY, 0, HOT_AIR_SKYWAY,
    DB_PREFIX_LEVELIDS | N_GIN_LABS,     0, N_GIN_LABS,
    DB_PREFIX_LEVELIDS | OXIDE_STATION,  0, OXIDE_STATION,
    DB_PREFIX_LEVELIDS | SLIDE_COLISEUM, 0, SLIDE_COLISEUM,
    DB_PREFIX_LEVELIDS | TURBO_TRACK,    0, TURBO_TRACK,
    DB_PREFIX_LEVELIDS | SKULL_ROCK,     0, SKULL_ROCK,
    DB_PREFIX_LEVELIDS | RAMPAGE_RUINS,  0, RAMPAGE_RUINS,
    DB_PREFIX_LEVELIDS | ROCKY_ROAD,     0, ROCKY_ROAD,
    DB_PREFIX_LEVELIDS | NITRO_COURT,    0, NITRO_COURT,
    DB_PREFIX_LEVELIDS | CUP_RED,        0, CUP_RED,
    DB_PREFIX_LEVELIDS | CUP_GREEN,      0, CUP_GREEN,
    DB_PREFIX_LEVELIDS | CUP_BLUE,       0, CUP_BLUE,
    DB_PREFIX_LEVELIDS | CUP_YELLOW,     0, CUP_YELLOW,
    DB_PREFIX_LEVELIDS | CUP_PURPLE,     0, CUP_PURPLE,
    /* RACE UNLOCK REQUIREMENTS */
    DB_PREFIX_WARPPADUNLOCK_1 | CRASH_COVE,     0, STATIC_TROPHY | (0 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | CRASH_COVE,     0, STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | ROO_TUBES,      0, STATIC_TROPHY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | ROO_TUBES,      0, STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | TIGER_TEMPLE,   0, STATIC_TROPHY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | TIGER_TEMPLE,   0, STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | COCO_PARK,      0, STATIC_TROPHY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | COCO_PARK,      0, STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | MYSTERY_CAVES,  0, STATIC_TROPHY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | MYSTERY_CAVES,  0, STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | BLIZZARD_BLUFF, 0, STATIC_TROPHY | (8 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | BLIZZARD_BLUFF, 0, STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | SEWER_SPEEDWAY, 0, STATIC_TROPHY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | SEWER_SPEEDWAY, 0, STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | DINGO_CANYON,   0, STATIC_TROPHY | (7 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | DINGO_CANYON,   0, STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | PAPU_PYRAMID,   0, STATIC_TROPHY | (6 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | PAPU_PYRAMID,   0, STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | DRAGON_MINES,   0, STATIC_TROPHY | (9 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | DRAGON_MINES,   0, STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | POLAR_PASS,     0, STATIC_TROPHY | (10 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | POLAR_PASS,     0, STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CORTEX_CASTLE,  0, STATIC_TROPHY | (12 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | CORTEX_CASTLE,  0, STATIC_KEY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | TINY_ARENA,     0, STATIC_TROPHY | (11 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | TINY_ARENA,     0, STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | HOT_AIR_SKYWAY, 0, STATIC_TROPHY | (14 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | HOT_AIR_SKYWAY, 0, STATIC_KEY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | N_GIN_LABS,     0, STATIC_TROPHY | (12 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | N_GIN_LABS,     0, STATIC_KEY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | OXIDE_STATION,  0, STATIC_TROPHY | (15 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | OXIDE_STATION,  0, STATIC_KEY | (4 << 16),
    /* RACE UNLOCK REQUIREMENTS RELIC ONLY TRACKS*/
    DB_PREFIX_WARPPADUNLOCK_1 | SLIDE_COLISEUM, 0, STATIC_RELIC | (RELIC_SAPPHIRE << 8) | (10 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | TURBO_TRACK,    0, STATIC_GEM | (GEM_ANY << 8) | (5 << 16),
    /* RACE UNLOCK REQUIREMENTS CRYSTAL CHALLENGES */
    DB_PREFIX_WARPPADUNLOCK_1 | SKULL_ROCK,    0, STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | RAMPAGE_RUINS, 0, STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | ROCKY_ROAD,    0, STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | NITRO_COURT,   0, STATIC_KEY | (4 << 16),
    /* RACE UNLOCK REQUIREMENTS CUPS */
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_RED,    0, STATIC_TOKEN | (TOKEN_RED << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_GREEN,  0, STATIC_TOKEN | (TOKEN_GREEN << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_BLUE,   0, STATIC_TOKEN | (TOKEN_BLUE << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_YELLOW, 0, STATIC_TOKEN | (TOKEN_YELLOW << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_PURPLE, 0, STATIC_TOKEN | (TOKEN_PURPLE << 8) | (4 << 16),
    /* RACE REWARDS */
    DB_PREFIX_REWARDS | CRASH_COVE, STATIC_TROPHY,                             STATIC_TROPHY,
    DB_PREFIX_REWARDS | CRASH_COVE, STATIC_TOKEN,                              STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | CRASH_COVE, STATIC_RELIC | (RELIC_SAPPHIRE << 8),     STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | CRASH_COVE, STATIC_RELIC | (RELIC_GOLD << 8),         STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | CRASH_COVE, STATIC_RELIC | (RELIC_PLATINUM << 8),     STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | ROO_TUBES, STATIC_TROPHY,                              STATIC_TROPHY,
    DB_PREFIX_REWARDS | ROO_TUBES, STATIC_TOKEN,                               STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | ROO_TUBES, STATIC_RELIC | (RELIC_SAPPHIRE << 8),      STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | ROO_TUBES, STATIC_RELIC | (RELIC_GOLD << 8),          STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | ROO_TUBES, STATIC_RELIC | (RELIC_PLATINUM << 8),      STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | TIGER_TEMPLE, STATIC_TROPHY,                           STATIC_TROPHY,
    DB_PREFIX_REWARDS | TIGER_TEMPLE, STATIC_TOKEN,                            STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | TIGER_TEMPLE, STATIC_RELIC | (RELIC_SAPPHIRE << 8),   STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | TIGER_TEMPLE, STATIC_RELIC | (RELIC_GOLD << 8),       STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | TIGER_TEMPLE, STATIC_RELIC | (RELIC_PLATINUM << 8),   STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | COCO_PARK, STATIC_TROPHY,                              STATIC_TROPHY,
    DB_PREFIX_REWARDS | COCO_PARK, STATIC_TOKEN,                               STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | COCO_PARK, STATIC_RELIC | (RELIC_SAPPHIRE << 8),      STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | COCO_PARK, STATIC_RELIC | (RELIC_GOLD << 8),          STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | COCO_PARK, STATIC_RELIC | (RELIC_PLATINUM << 8),      STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | MYSTERY_CAVES, STATIC_TROPHY,                          STATIC_TROPHY,
    DB_PREFIX_REWARDS | MYSTERY_CAVES, STATIC_TOKEN,                           STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | MYSTERY_CAVES, STATIC_RELIC | (RELIC_SAPPHIRE << 8),  STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | MYSTERY_CAVES, STATIC_RELIC | (RELIC_GOLD << 8),      STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | MYSTERY_CAVES, STATIC_RELIC | (RELIC_PLATINUM << 8),  STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | BLIZZARD_BLUFF, STATIC_TROPHY,                         STATIC_TROPHY,
    DB_PREFIX_REWARDS | BLIZZARD_BLUFF, STATIC_TOKEN,                          STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | BLIZZARD_BLUFF, STATIC_RELIC | (RELIC_SAPPHIRE << 8), STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | BLIZZARD_BLUFF, STATIC_RELIC | (RELIC_GOLD << 8),     STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | BLIZZARD_BLUFF, STATIC_RELIC | (RELIC_PLATINUM << 8), STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | SEWER_SPEEDWAY, STATIC_TROPHY,                         STATIC_TROPHY,
    DB_PREFIX_REWARDS | SEWER_SPEEDWAY, STATIC_TOKEN,                          STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | SEWER_SPEEDWAY, STATIC_RELIC | (RELIC_SAPPHIRE << 8), STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | SEWER_SPEEDWAY, STATIC_RELIC | (RELIC_GOLD << 8),     STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | SEWER_SPEEDWAY, STATIC_RELIC | (RELIC_PLATINUM << 8), STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | DINGO_CANYON, STATIC_TROPHY,                           STATIC_TROPHY,
    DB_PREFIX_REWARDS | DINGO_CANYON, STATIC_TOKEN,                            STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | DINGO_CANYON, STATIC_RELIC | (RELIC_SAPPHIRE << 8),   STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | DINGO_CANYON, STATIC_RELIC | (RELIC_GOLD << 8),       STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | DINGO_CANYON, STATIC_RELIC | (RELIC_PLATINUM << 8),   STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | PAPU_PYRAMID, STATIC_TROPHY,                           STATIC_TROPHY,
    DB_PREFIX_REWARDS | PAPU_PYRAMID, STATIC_TOKEN,                            STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | PAPU_PYRAMID, STATIC_RELIC | (RELIC_SAPPHIRE << 8),   STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | PAPU_PYRAMID, STATIC_RELIC | (RELIC_GOLD << 8),       STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | PAPU_PYRAMID, STATIC_RELIC | (RELIC_PLATINUM << 8),   STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | DRAGON_MINES, STATIC_TROPHY,                           STATIC_TROPHY,
    DB_PREFIX_REWARDS | DRAGON_MINES, STATIC_TOKEN,                            STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | DRAGON_MINES, STATIC_RELIC | (RELIC_SAPPHIRE << 8),   STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | DRAGON_MINES, STATIC_RELIC | (RELIC_GOLD << 8),       STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | DRAGON_MINES, STATIC_RELIC | (RELIC_PLATINUM << 8),   STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | POLAR_PASS, STATIC_TROPHY,                             STATIC_TROPHY,
    DB_PREFIX_REWARDS | POLAR_PASS, STATIC_TOKEN,                              STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | POLAR_PASS, STATIC_RELIC | (RELIC_SAPPHIRE << 8),     STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | POLAR_PASS, STATIC_RELIC | (RELIC_GOLD << 8),         STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | POLAR_PASS, STATIC_RELIC | (RELIC_PLATINUM << 8),     STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | CORTEX_CASTLE, STATIC_TROPHY,                          STATIC_TROPHY,
    DB_PREFIX_REWARDS | CORTEX_CASTLE, STATIC_TOKEN,                           STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | CORTEX_CASTLE, STATIC_RELIC | (RELIC_SAPPHIRE << 8),  STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | CORTEX_CASTLE, STATIC_RELIC | (RELIC_GOLD << 8),      STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | CORTEX_CASTLE, STATIC_RELIC | (RELIC_PLATINUM << 8),  STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | TINY_ARENA, STATIC_TROPHY,                             STATIC_TROPHY,
    DB_PREFIX_REWARDS | TINY_ARENA, STATIC_TOKEN,                              STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | TINY_ARENA, STATIC_RELIC | (RELIC_SAPPHIRE << 8),     STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | TINY_ARENA, STATIC_RELIC | (RELIC_GOLD << 8),         STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | TINY_ARENA, STATIC_RELIC | (RELIC_PLATINUM << 8),     STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | HOT_AIR_SKYWAY, STATIC_TROPHY,                         STATIC_TROPHY,
    DB_PREFIX_REWARDS | HOT_AIR_SKYWAY, STATIC_TOKEN,                          STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | HOT_AIR_SKYWAY, STATIC_RELIC | (RELIC_SAPPHIRE << 8), STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | HOT_AIR_SKYWAY, STATIC_RELIC | (RELIC_GOLD << 8),     STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | HOT_AIR_SKYWAY, STATIC_RELIC | (RELIC_PLATINUM << 8), STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | N_GIN_LABS, STATIC_TROPHY,                             STATIC_TROPHY,
    DB_PREFIX_REWARDS | N_GIN_LABS, STATIC_TOKEN,                              STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | N_GIN_LABS, STATIC_RELIC | (RELIC_SAPPHIRE << 8),     STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | N_GIN_LABS, STATIC_RELIC | (RELIC_GOLD << 8),         STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | N_GIN_LABS, STATIC_RELIC | (RELIC_PLATINUM << 8),     STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | OXIDE_STATION, STATIC_TROPHY,                          STATIC_TROPHY,
    DB_PREFIX_REWARDS | OXIDE_STATION, STATIC_TOKEN,                           STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | OXIDE_STATION, STATIC_RELIC | (RELIC_SAPPHIRE << 8),  STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | OXIDE_STATION, STATIC_RELIC | (RELIC_GOLD << 8),      STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | OXIDE_STATION, STATIC_RELIC | (RELIC_PLATINUM << 8),  STATIC_RELIC | (RELIC_PLATINUM << 8),
    /* RACE REWARDS RELIC ONLY TRACKS*/
    DB_PREFIX_REWARDS | SLIDE_COLISEUM, STATIC_RELIC | (RELIC_SAPPHIRE << 8), STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | SLIDE_COLISEUM, STATIC_RELIC | (RELIC_GOLD << 8),     STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | SLIDE_COLISEUM, STATIC_RELIC | (RELIC_PLATINUM << 8), STATIC_RELIC | (RELIC_PLATINUM << 8),
    DB_PREFIX_REWARDS | TURBO_TRACK, STATIC_RELIC | (RELIC_SAPPHIRE << 8),    STATIC_RELIC | (RELIC_SAPPHIRE << 8),
    DB_PREFIX_REWARDS | TURBO_TRACK, STATIC_RELIC | (RELIC_GOLD << 8),        STATIC_RELIC | (RELIC_GOLD << 8),
    DB_PREFIX_REWARDS | TURBO_TRACK, STATIC_RELIC | (RELIC_PLATINUM << 8),    STATIC_RELIC | (RELIC_PLATINUM << 8),
    /* RACE REWARDS CRYSTAL CHALLENGES */
    DB_PREFIX_REWARDS | SKULL_ROCK, STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_PURPLE << 8),
    DB_PREFIX_REWARDS | RAMPAGE_RUINS, STATIC_TOKEN,   STATIC_TOKEN | (TOKEN_PURPLE << 8),
    DB_PREFIX_REWARDS | ROCKY_ROAD, STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_PURPLE << 8),
    DB_PREFIX_REWARDS | NITRO_COURT, STATIC_TOKEN,     STATIC_TOKEN | (TOKEN_PURPLE << 8),
    /* RACE REWARDS BOSSES */
    DB_PREFIX_REWARDS | ROO_TUBES, STATIC_KEY,         STATIC_KEY,
    DB_PREFIX_REWARDS | PAPU_PYRAMID, STATIC_KEY,      STATIC_KEY,
    DB_PREFIX_REWARDS | DRAGON_MINES, STATIC_KEY,      STATIC_KEY,
    DB_PREFIX_REWARDS | HOT_AIR_SKYWAY, STATIC_KEY,    STATIC_KEY,
    /* RACE REWARDS CUPS */
    DB_PREFIX_REWARDS | CUP_RED, STATIC_GEM,           STATIC_GEM | (GEM_RED << 8),
    DB_PREFIX_REWARDS | CUP_GREEN, STATIC_GEM,         STATIC_GEM | (GEM_GREEN << 8),
    DB_PREFIX_REWARDS | CUP_BLUE, STATIC_GEM,          STATIC_GEM | (GEM_BLUE << 8),
    DB_PREFIX_REWARDS | CUP_YELLOW, STATIC_GEM,        STATIC_GEM | (GEM_YELLOW << 8),
    DB_PREFIX_REWARDS | CUP_PURPLE, STATIC_GEM,        STATIC_GEM | (GEM_PURPLE << 8),
    /* SEED SETTINGS */
    DB_PREFIX_SETTINGS | SETTING_RELIC_DIFFICULTY,      0, RELICDIFF_SAPPHIRE,
    DB_PREFIX_SETTINGS | SETTING_RELIC_NEEDS_PERFECT,   0, FALSE,
    DB_PREFIX_SETTINGS | SETTING_BOSS_GARAGE_OPENING,   0, GARAGE_OPENING_VANILLA_WARPPADS,
    DB_PREFIX_SETTINGS | SETTING_QOL_SKIP_MASKHINTS,    0, TRUE,
    DB_PREFIX_SETTINGS | SETTING_QOL_SKIP_PODIUM,       0, FALSE,
    DB_PREFIX_SETTINGS | SETTING_QOL_SKIP_CONGRATS,     0, FALSE,
    DB_PREFIX_SETTINGS | SETTING_OXIDE_REQUIRED_RELICS, 0, RELIC_SAPPHIRE,
    DB_RAMMARKER_END,
    DB_END
};
