#include <common.h>
#include "CTRRandomizer_database.h"
#include "reward_enums.h"

#ifndef FALSE
#define FALSE  0
#endif

#ifndef TRUE
#define TRUE  1
#endif

#define DB_END -1
#define DB_RAMMARKER_START 0xDADB0D00, 0xDADB0D00
#define DB_RAMMARKER_END 0xDADB0DAA, 0xDADB0DAA

static int rando_database[];

/* Potentially removable, since it mirrors the GemColor enum */
enum CupIds {
    CUP_RED = 100,
    CUP_GREEN,
    CUP_BLUE,
    CUP_YELLOW,
    CUP_PURPLE
};

/*
Fetch a value from the randomizer database using the given key.
If the value cannot be found, return the key as value and set the
fetch result to not_found.
This function is sped up using dynamic jump offsets, making subsequent queries
faster. However, this requires the settings to be grouped by types, instead
of being randomly arranged.
*/
int database_fetch(
    int db_key,
    int *fetch_result
)
{
    static int db_offset_rewards = 0;
    static int db_offset_settings = 0;
    int i = 0;

    // If we have db offsets from a previous fetch call, use them to skip
    // a bunch of entries
    if (   (db_offset_settings != 0)
        && (db_key & DB_PREFIX_SETTINGS) == DB_PREFIX_SETTINGS
    )
    {
        i = db_offset_settings;
    }
    else if (   (db_offset_rewards != 0)
             && (db_key & DB_PREFIX_REWARDS) == DB_PREFIX_REWARDS
    )
    {
        i = db_offset_rewards;
    }

    for (; rando_database[i] != DB_END; i += 2)
    {
        // If we have un-set db offsets, check if we have found the first
        // matching entry and, if so, set the offset jump value
        if (   db_offset_rewards == 0
            && (rando_database[i] & DB_PREFIX_REWARDS) == DB_PREFIX_REWARDS
        )
        {
            db_offset_rewards = i;
        }

        if (   db_offset_settings == 0
            && (rando_database[i] & DB_PREFIX_SETTINGS) == DB_PREFIX_SETTINGS
        )
        {
            db_offset_settings = i;
        }

        // If we have found our value, set output
        if (rando_database[i] == db_key)
        {
            *fetch_result = DB_VALUE_OK;
            return rando_database[i + 1];
        }
    }

    // If we get here, then we didn't find what we were looking for
    *fetch_result = DB_VALUE_NOTFOUND;
    return db_key;
}

static int rando_database[] = {
    DB_RAMMARKER_START,
    /* LEVEL IDS FOR RANDOM WARP PADS */
    DB_PREFIX_LEVELIDS | CRASH_COVE,     CRASH_COVE,
    DB_PREFIX_LEVELIDS | ROO_TUBES,      ROO_TUBES,
    DB_PREFIX_LEVELIDS | TIGER_TEMPLE,   TIGER_TEMPLE,
    DB_PREFIX_LEVELIDS | COCO_PARK,      COCO_PARK,
    DB_PREFIX_LEVELIDS | MYSTERY_CAVES,  MYSTERY_CAVES,
    DB_PREFIX_LEVELIDS | BLIZZARD_BLUFF, BLIZZARD_BLUFF,
    DB_PREFIX_LEVELIDS | SEWER_SPEEDWAY, SEWER_SPEEDWAY,
    DB_PREFIX_LEVELIDS | DINGO_CANYON,   DINGO_CANYON,
    DB_PREFIX_LEVELIDS | PAPU_PYRAMID,   PAPU_PYRAMID,
    DB_PREFIX_LEVELIDS | DRAGON_MINES,   DRAGON_MINES,
    DB_PREFIX_LEVELIDS | POLAR_PASS,     POLAR_PASS,
    DB_PREFIX_LEVELIDS | CORTEX_CASTLE,  CORTEX_CASTLE,
    DB_PREFIX_LEVELIDS | TINY_ARENA,     TINY_ARENA,
    DB_PREFIX_LEVELIDS | HOT_AIR_SKYWAY, HOT_AIR_SKYWAY,
    DB_PREFIX_LEVELIDS | N_GIN_LABS,     N_GIN_LABS,
    DB_PREFIX_LEVELIDS | OXIDE_STATION,  OXIDE_STATION,
    DB_PREFIX_LEVELIDS | SLIDE_COLISEUM, SLIDE_COLISEUM,
    DB_PREFIX_LEVELIDS | TURBO_TRACK,    TURBO_TRACK,
    DB_PREFIX_LEVELIDS | SKULL_ROCK,     SKULL_ROCK,
    DB_PREFIX_LEVELIDS | RAMPAGE_RUINS,  RAMPAGE_RUINS,
    DB_PREFIX_LEVELIDS | ROCKY_ROAD,     ROCKY_ROAD,
    DB_PREFIX_LEVELIDS | NITRO_COURT,    NITRO_COURT,
    /* RACE UNLOCK REQUIREMENTS */
    DB_PREFIX_WARPPADUNLOCK_1 | CRASH_COVE,     STATIC_TROPHY | (0 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | CRASH_COVE,     STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | ROO_TUBES,      STATIC_TROPHY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | ROO_TUBES,      STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | TIGER_TEMPLE,   STATIC_TROPHY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | TIGER_TEMPLE,   STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | COCO_PARK,      STATIC_TROPHY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | COCO_PARK,      STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | MYSTERY_CAVES,  STATIC_TROPHY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | MYSTERY_CAVES,  STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | BLIZZARD_BLUFF, STATIC_TROPHY | (8 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | BLIZZARD_BLUFF, STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | SEWER_SPEEDWAY, STATIC_TROPHY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | SEWER_SPEEDWAY, STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | DINGO_CANYON,   STATIC_TROPHY | (7 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | DINGO_CANYON,   STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | PAPU_PYRAMID,   STATIC_TROPHY | (6 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | PAPU_PYRAMID,   STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | DRAGON_MINES,   STATIC_TROPHY | (9 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | DRAGON_MINES,   STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | POLAR_PASS,     STATIC_TROPHY | (10 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | POLAR_PASS,     STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CORTEX_CASTLE,  STATIC_TROPHY | (12 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | CORTEX_CASTLE,  STATIC_KEY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | TINY_ARENA,     STATIC_TROPHY | (11 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | TINY_ARENA,     STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | HOT_AIR_SKYWAY, STATIC_TROPHY | (14 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | HOT_AIR_SKYWAY, STATIC_KEY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | N_GIN_LABS,     STATIC_TROPHY | (12 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | N_GIN_LABS,     STATIC_KEY | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | OXIDE_STATION,  STATIC_TROPHY | (15 << 16),
    DB_PREFIX_WARPPADUNLOCK_2 | OXIDE_STATION,  STATIC_KEY | (4 << 16),
    /* RACE UNLOCK REQUIREMENTS RELIC ONLY TRACKS*/
    DB_PREFIX_WARPPADUNLOCK_1 | SLIDE_COLISEUM, STATIC_RELIC | (10 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | TURBO_TRACK,    STATIC_GEM | (GEM_ANY << 8) | (5 << 16),
    /* RACE UNLOCK REQUIREMENTS CRYSTAL CHALLENGES */
    DB_PREFIX_WARPPADUNLOCK_1 | SKULL_ROCK,    STATIC_KEY | (1 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | RAMPAGE_RUINS, STATIC_KEY | (2 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | ROCKY_ROAD,    STATIC_KEY | (3 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | NITRO_COURT,   STATIC_KEY | (4 << 16),
    /* RACE UNLOCK REQUIREMENTS CUPS */
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_RED,    STATIC_TOKEN | (TOKEN_RED << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_GREEN,  STATIC_TOKEN | (TOKEN_GREEN << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_BLUE,   STATIC_TOKEN | (TOKEN_BLUE << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_YELLOW, STATIC_TOKEN | (TOKEN_YELLOW << 8) | (4 << 16),
    DB_PREFIX_WARPPADUNLOCK_1 | CUP_PURPLE, STATIC_TOKEN | (TOKEN_PURPLE << 8) | (4 << 16),
    /* RACE REWARDS */
    DB_PREFIX_REWARDS | (CRASH_COVE << 8) | STATIC_TROPHY,     STATIC_TROPHY,
    DB_PREFIX_REWARDS | (CRASH_COVE << 8) | STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | (CRASH_COVE << 8) | STATIC_RELIC,      STATIC_RELIC,
    DB_PREFIX_REWARDS | (ROO_TUBES << 8) | STATIC_TROPHY,      STATIC_TROPHY,
    DB_PREFIX_REWARDS | (ROO_TUBES << 8) | STATIC_TOKEN,       STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | (ROO_TUBES << 8) | STATIC_RELIC,       STATIC_RELIC,
    DB_PREFIX_REWARDS | (TIGER_TEMPLE << 8) | STATIC_TROPHY,   STATIC_TROPHY,
    DB_PREFIX_REWARDS | (TIGER_TEMPLE << 8) | STATIC_TOKEN,    STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | (TIGER_TEMPLE << 8) | STATIC_RELIC,    STATIC_RELIC,
    DB_PREFIX_REWARDS | (COCO_PARK << 8) | STATIC_TROPHY,      STATIC_TROPHY,
    DB_PREFIX_REWARDS | (COCO_PARK << 8) | STATIC_TOKEN,       STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | (COCO_PARK << 8) | STATIC_RELIC,       STATIC_RELIC,
    DB_PREFIX_REWARDS | (MYSTERY_CAVES << 8) | STATIC_TROPHY,  STATIC_TROPHY,
    DB_PREFIX_REWARDS | (MYSTERY_CAVES << 8) | STATIC_TOKEN,   STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | (MYSTERY_CAVES << 8) | STATIC_RELIC,   STATIC_RELIC,
    DB_PREFIX_REWARDS | (BLIZZARD_BLUFF << 8) | STATIC_TROPHY, STATIC_TROPHY,
    DB_PREFIX_REWARDS | (BLIZZARD_BLUFF << 8) | STATIC_TOKEN,  STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | (BLIZZARD_BLUFF << 8) | STATIC_RELIC,  STATIC_RELIC,
    DB_PREFIX_REWARDS | (SEWER_SPEEDWAY << 8) | STATIC_TROPHY, STATIC_TROPHY,
    DB_PREFIX_REWARDS | (SEWER_SPEEDWAY << 8) | STATIC_TOKEN,  STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | (SEWER_SPEEDWAY << 8) | STATIC_RELIC,  STATIC_RELIC,
    DB_PREFIX_REWARDS | (DINGO_CANYON << 8) | STATIC_TROPHY,   STATIC_TROPHY,
    DB_PREFIX_REWARDS | (DINGO_CANYON << 8) | STATIC_TOKEN,    STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | (DINGO_CANYON << 8) | STATIC_RELIC,    STATIC_RELIC,
    DB_PREFIX_REWARDS | (PAPU_PYRAMID << 8) | STATIC_TROPHY,   STATIC_TROPHY,
    DB_PREFIX_REWARDS | (PAPU_PYRAMID << 8) | STATIC_TOKEN,    STATIC_TOKEN | (TOKEN_RED << 8),
    DB_PREFIX_REWARDS | (PAPU_PYRAMID << 8) | STATIC_RELIC,    STATIC_RELIC,
    DB_PREFIX_REWARDS | (DRAGON_MINES << 8) | STATIC_TROPHY,   STATIC_TROPHY,
    DB_PREFIX_REWARDS | (DRAGON_MINES << 8) | STATIC_TOKEN,    STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | (DRAGON_MINES << 8) | STATIC_RELIC,    STATIC_RELIC,
    DB_PREFIX_REWARDS | (POLAR_PASS << 8) | STATIC_TROPHY,     STATIC_TROPHY,
    DB_PREFIX_REWARDS | (POLAR_PASS << 8) | STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | (POLAR_PASS << 8) | STATIC_RELIC,      STATIC_RELIC,
    DB_PREFIX_REWARDS | (CORTEX_CASTLE << 8) | STATIC_TROPHY,  STATIC_TROPHY,
    DB_PREFIX_REWARDS | (CORTEX_CASTLE << 8) | STATIC_TOKEN,   STATIC_TOKEN | (TOKEN_GREEN << 8),
    DB_PREFIX_REWARDS | (CORTEX_CASTLE << 8) | STATIC_RELIC,   STATIC_RELIC,
    DB_PREFIX_REWARDS | (TINY_ARENA << 8) | STATIC_TROPHY,     STATIC_TROPHY,
    DB_PREFIX_REWARDS | (TINY_ARENA << 8) | STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | (TINY_ARENA << 8) | STATIC_RELIC,      STATIC_RELIC,
    DB_PREFIX_REWARDS | (HOT_AIR_SKYWAY << 8) | STATIC_TROPHY, STATIC_TROPHY,
    DB_PREFIX_REWARDS | (HOT_AIR_SKYWAY << 8) | STATIC_TOKEN,  STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | (HOT_AIR_SKYWAY << 8) | STATIC_RELIC,  STATIC_RELIC,
    DB_PREFIX_REWARDS | (N_GIN_LABS << 8) | STATIC_TROPHY,     STATIC_TROPHY,
    DB_PREFIX_REWARDS | (N_GIN_LABS << 8) | STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_BLUE << 8),
    DB_PREFIX_REWARDS | (N_GIN_LABS << 8) | STATIC_RELIC,      STATIC_RELIC,
    DB_PREFIX_REWARDS | (OXIDE_STATION << 8) | STATIC_TROPHY,  STATIC_TROPHY,
    DB_PREFIX_REWARDS | (OXIDE_STATION << 8) | STATIC_TOKEN,   STATIC_TOKEN | (TOKEN_YELLOW << 8),
    DB_PREFIX_REWARDS | (OXIDE_STATION << 8) | STATIC_RELIC,   STATIC_RELIC,
    /* RACE REWARDS RELIC ONLY TRACKS*/
    DB_PREFIX_REWARDS | (SLIDE_COLISEUM << 8) | STATIC_RELIC,  STATIC_RELIC,
    DB_PREFIX_REWARDS | (TURBO_TRACK << 8) | STATIC_RELIC,     STATIC_RELIC,
    /* RACE REWARDS CRYSTAL CHALLENGES */
    DB_PREFIX_REWARDS | (SKULL_ROCK << 8) | STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_PURPLE << 8),
    DB_PREFIX_REWARDS | (RAMPAGE_RUINS << 8) | STATIC_TOKEN,   STATIC_TOKEN | (TOKEN_PURPLE << 8),
    DB_PREFIX_REWARDS | (ROCKY_ROAD << 8) | STATIC_TOKEN,      STATIC_TOKEN | (TOKEN_PURPLE << 8),
    DB_PREFIX_REWARDS | (NITRO_COURT << 8) | STATIC_TOKEN,     STATIC_TOKEN | (TOKEN_PURPLE << 8),
    /* RACE REWARDS BOSSES */
    DB_PREFIX_REWARDS | (ROO_TUBES << 8) | STATIC_KEY,         STATIC_KEY,
    DB_PREFIX_REWARDS | (PAPU_PYRAMID << 8) | STATIC_KEY,      STATIC_KEY,
    DB_PREFIX_REWARDS | (DRAGON_MINES << 8) | STATIC_KEY,      STATIC_KEY,
    DB_PREFIX_REWARDS | (HOT_AIR_SKYWAY << 8) | STATIC_KEY,    STATIC_KEY,
    /* RACE REWARDS CUPS */
    DB_PREFIX_REWARDS | (CUP_RED << 8) | STATIC_GEM,           STATIC_GEM | (GEM_RED << 8),
    DB_PREFIX_REWARDS | (CUP_GREEN << 8) | STATIC_GEM,         STATIC_GEM | (GEM_GREEN << 8),
    DB_PREFIX_REWARDS | (CUP_BLUE << 8) | STATIC_GEM,          STATIC_GEM | (GEM_BLUE << 8),
    DB_PREFIX_REWARDS | (CUP_YELLOW << 8) | STATIC_GEM,        STATIC_GEM | (GEM_YELLOW << 8),
    DB_PREFIX_REWARDS | (CUP_PURPLE << 8) | STATIC_GEM,        STATIC_GEM | (GEM_PURPLE << 8),
    /* SEED SETTINGS */
    DB_PREFIX_SETTINGS | SETTING_RELIC_DIFFICULTY,    RELICDIFF_SAPPHIRE,
    DB_PREFIX_SETTINGS | SETTING_RELIC_NEEDS_PERFECT, FALSE,
    DB_PREFIX_SETTINGS | SETTING_BOSS_GARAGE_OPENING, GARAGE_OPENING_VANILLA_WARPPADS,
    DB_PREFIX_SETTINGS | SETTING_QOL_SKIP_MASKHINTS,  TRUE,
    DB_PREFIX_SETTINGS | SETTING_QOL_SKIP_PODIUM,     FALSE,
    DB_PREFIX_SETTINGS | SETTING_QOL_SKIP_CONGRATS,   FALSE,
    DB_RAMMARKER_END,
    DB_END
};
