#include <common.h>
#include "CTRRandomizer_database.h"

#define DB_END -1
#define DB_RAMMARKER_START 0xDADB0D00, 0xDADB0D00
#define DB_RAMMARKER_END 0xDADB0DAA, 0xDADB0DAA

static int rando_database[] = {
    DB_RAMMARKER_START,
    DB_PREFIX_LEVELIDS | CRASH_COVE,     CRASH_COVE,
    DB_PREFIX_LEVELIDS | ROO_TUBES,      ROO_TUBES,
    DB_PREFIX_LEVELIDS | TIGER_TEMPLE,   TIGER_TEMPLE,
    DB_PREFIX_LEVELIDS | COCO_PARK,      COCO_PARK,
    DB_PREFIX_LEVELIDS | MYSTERY_CAVES,  MYSTERY_CAVES,
    DB_PREFIX_LEVELIDS | BLIZZARD_BLUFF, BLIZZARD_BLUFF,
    DB_PREFIX_LEVELIDS | SEWER_SPEEDWAY, SEWER_SPEEDWAY,
    DB_PREFIX_LEVELIDS | DINGO_CANYON,   DINGO_CANYON,
    DB_PREFIX_LEVELIDS | PAPU_PYRAMID,   PAPU_PYRAMID,
    DB_PREFIX_LEVELIDS | DRAGON_MINES,   DRAGON_MINES,
    DB_PREFIX_LEVELIDS | POLAR_PASS,     POLAR_PASS,
    DB_PREFIX_LEVELIDS | CORTEX_CASTLE,  CORTEX_CASTLE,
    DB_PREFIX_LEVELIDS | TINY_ARENA,     TINY_ARENA,
    DB_PREFIX_LEVELIDS | HOT_AIR_SKYWAY, HOT_AIR_SKYWAY,
    DB_PREFIX_LEVELIDS | N_GIN_LABS,     N_GIN_LABS,
    DB_PREFIX_LEVELIDS | OXIDE_STATION,  OXIDE_STATION,
    DB_PREFIX_LEVELIDS | SLIDE_COLISEUM, SLIDE_COLISEUM,
    DB_PREFIX_LEVELIDS | TURBO_TRACK,    TURBO_TRACK,
    DB_PREFIX_LEVELIDS | SKULL_ROCK,     SKULL_ROCK,
    DB_PREFIX_LEVELIDS | RAMPAGE_RUINS,  RAMPAGE_RUINS,
    DB_PREFIX_LEVELIDS | ROCKY_ROAD,     ROCKY_ROAD,
    DB_PREFIX_LEVELIDS | NITRO_COURT,    NITRO_COURT,
    DB_PREFIX_UNLOCK_ITEMTYPE | CRASH_COVE,     STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | ROO_TUBES,      STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | TIGER_TEMPLE,   STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | COCO_PARK,      STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | MYSTERY_CAVES,  STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | BLIZZARD_BLUFF, STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | SEWER_SPEEDWAY, STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | DINGO_CANYON,   STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | PAPU_PYRAMID,   STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | DRAGON_MINES,   STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | POLAR_PASS,     STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | CORTEX_CASTLE,  STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | TINY_ARENA,     STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | HOT_AIR_SKYWAY, STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | N_GIN_LABS,     STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | OXIDE_STATION,  STATIC_TROPHY,
    DB_PREFIX_UNLOCK_ITEMTYPE | SLIDE_COLISEUM, STATIC_RELIC,
    DB_PREFIX_UNLOCK_ITEMTYPE | TURBO_TRACK,    STATIC_GEM,
    DB_PREFIX_UNLOCK_ITEMTYPE | SKULL_ROCK,     STATIC_KEY,
    DB_PREFIX_UNLOCK_ITEMTYPE | RAMPAGE_RUINS,  STATIC_KEY,
    DB_PREFIX_UNLOCK_ITEMTYPE | ROCKY_ROAD,     STATIC_KEY,
    DB_PREFIX_UNLOCK_ITEMTYPE | NITRO_COURT,    STATIC_KEY,
    DB_PREFIX_UNLOCK_ITEMCOUNT | CRASH_COVE,     0,
    DB_PREFIX_UNLOCK_ITEMCOUNT | ROO_TUBES,      0,
    DB_PREFIX_UNLOCK_ITEMCOUNT | TIGER_TEMPLE,   4,
    DB_PREFIX_UNLOCK_ITEMCOUNT | COCO_PARK,      4,
    DB_PREFIX_UNLOCK_ITEMCOUNT | MYSTERY_CAVES,  1,
    DB_PREFIX_UNLOCK_ITEMCOUNT | BLIZZARD_BLUFF, 8,
    DB_PREFIX_UNLOCK_ITEMCOUNT | SEWER_SPEEDWAY, 3,
    DB_PREFIX_UNLOCK_ITEMCOUNT | DINGO_CANYON,   7,
    DB_PREFIX_UNLOCK_ITEMCOUNT | PAPU_PYRAMID,   6,
    DB_PREFIX_UNLOCK_ITEMCOUNT | DRAGON_MINES,   9,
    DB_PREFIX_UNLOCK_ITEMCOUNT | POLAR_PASS,     10,
    DB_PREFIX_UNLOCK_ITEMCOUNT | CORTEX_CASTLE,  12,
    DB_PREFIX_UNLOCK_ITEMCOUNT | TINY_ARENA,     11,
    DB_PREFIX_UNLOCK_ITEMCOUNT | HOT_AIR_SKYWAY, 14,
    DB_PREFIX_UNLOCK_ITEMCOUNT | N_GIN_LABS,     12,
    DB_PREFIX_UNLOCK_ITEMCOUNT | OXIDE_STATION,  15,
    DB_PREFIX_UNLOCK_ITEMCOUNT | SLIDE_COLISEUM, 10,
    DB_PREFIX_UNLOCK_ITEMCOUNT | TURBO_TRACK,    5,
    DB_PREFIX_UNLOCK_ITEMCOUNT | SKULL_ROCK,     1,
    DB_PREFIX_UNLOCK_ITEMCOUNT | RAMPAGE_RUINS,  2,
    DB_PREFIX_UNLOCK_ITEMCOUNT | ROCKY_ROAD,     3,
    DB_PREFIX_UNLOCK_ITEMCOUNT | NITRO_COURT,    4,
    DB_RAMMARKER_END,
    DB_END
};


/*
Fetch a value from the randomizer database using the given key.
If the value cannot be found, return the key as value and set the
fetch result to not_found.
*/
int database_fetch(
    int db_key,
    int *fetch_result
)
{
    for (int i = 0; rando_database[i] != DB_END; i += 2)
    {
        if (rando_database[i] == db_key)
        {
            *fetch_result = DB_VALUE_OK;
            return rando_database[i + 1];
        }
    }

    *fetch_result = DB_VALUE_NOTFOUND;
    return db_key;
}
